### ISSUE TITLE
Disable snapshots when update

### ISSUE THREAD

**Issue by hubrikt** [BassT23/Proxmox#103]
Hello,

I see that snapshots are now supported and activated by default.
However, for those that we already have setup our backup system, maybe is not required or desired.
After checking the last release notes and the "update.conf" file I can't see how to disable taking snapshots before update.

Is that possible or snapshots are mandatory with this new version of Proxmox-Updater?
Thanks!

**Comment by BassT23** [comment]
Disable snapshot is not supported for now, but I will implement it :)

**Comment by BassT23** [comment]
implement in latest develop version - feel free to test, but please don't run a development version in productive Proxmox system - its not tested totally.
`update develop -up`

**Comment by hubrikt** [comment]
Updated to develop branch to test.
Feature is working as expected, changing to to "snapshots=false" within "update.conf" file .

Thanks a lot.
As soon as merged in master branch, I will come back to it :)
