### ISSUE TITLE
Uninstall : crontab

### ISSUE THREAD

**Issue by scaf13** [BassT23/Proxmox#104]
Hello,

After uninstall with bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/master/install.sh) uninstall

An error appear in my crontab :

/bin/sh: 1: /root/Proxmox-Updater/check-updates.sh: not found

The command crontab -e and crontab -l return no line with check-updates.sh

**Comment by BassT23** [comment]
Hi,

what give `cat /etc/crontab` out?
If there is any input with `check-updates.sh`, please comment out the line with `#` or delete the line completely

**Comment by scaf13** [comment]
Nothing : 

# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.daily; }
47 6    * * 7   root    test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.weekly; }
52 6    1 * *   root    test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.monthly; }
#

**Comment by BassT23** [comment]
ok, crontab seems ok, so please describe me more the "problem"
```
An error appear in my crontab :
/bin/sh: 1: /root/Proxmox-Updater/check-updates.sh: not found
```
where do you find it?
when come the "problem" up?

**Comment by scaf13** [comment]
I reboot my server and the problem is solved.
