### ISSUE TITLE
Snapshot LXC with mounted CIFS

### ISSUE THREAD

**Issue by Shotte** [BassT23/Proxmox#125]
Currently I'm not able to Snapshot an LXC if a CIFS volume is mounted (but updates are still done, thus this part is fine). 

A possible workaround is to unmount the CIFS volume, making a Snapshot and mount CIFS again. But this is pretty ugly work to do it maniually. Isn't it possible to change the script to this work automaically?

By the way: Thank you for this very good work!

EDIT:
[Fix by @Shotte](https://github.com/BassT23/Proxmox/issues/125#issuecomment-2529035820)

**Comment by BassT23** [comment]
I will have a look ;)

**Comment by pythongod** [comment]
I don't think i have this problem. Are your LXC Privileged?

**Comment by Shotte** [comment]
@pythongod No, they are not privileged. I have this problem. Only when I unmount CIFS mounts I can perform snapshots. Backups are no problem.

**Comment by BassT23** [comment]
> @pythongod No, they are not privileged. I have this problem. Only when I unmount CIFS mounts I can perform snapshots. Backups are no problem.

How did you mount the share? With fstab in container, or in cfg file from Proxmox?

**Comment by Shotte** [comment]
@BassT23 
I mount it using the following steps:
1. pvesm add cifs nas-software --server 192.168.xx.yy --share Software --username <user> --password <pw>
2. added in /etc/pve/storage.cfg for each mount "options file_mode=0777,dir_mode=0777" to make it writable for LXC
3. pct set <id> -mp0 /mnt/pve/nas-software,mp=/media/software

That's it. This gives me the advantage seeing the mounts in the PVE tree.

**Comment by BassT23** [comment]
First thanks to @Shotte and @pythongod, all your inspiration and comments are great for failer search :)

What we found out:
- cifs mount in previligated lxc with fstab in the lxc, there is no problem.
- if the storage is mounted in Proxmox conf, there are  issues with snapshot.

I could try to unmount the mp (or better complete storage) in Proxmox, during run the updater, but now I see a problem:
If the storeage is needed all the time in container, this could run in an big railure of the system #worstcase

So what I could try to do, I could ask the user during install for unmounting.

PS: I aslo use this form of mounting in an unprev container, but no snapshot support on this node for now ;)

**Comment by Shotte** [comment]
@BassT23 However, I'm now fine with your information because I konw now that I didn't do anything wrong regarding my configurations. Finally it is not a really big issue that you don't support it (where it is not your fault, so far as I undertstood). Many thankz to your very good work and your time. I will stay with your great piece of software ;-)

**Comment by Shotte** [comment]
@BassT23 meanwhile, I used the folling workaround:

1. open your lxc containter conf file (e.g. at /etc/pve/lxc/<container-id>.conf
2. change any cifs mountpoint entry to the following:
```
lxc.mount.entry: /mnt/pve/nas-musik media/musik none bind,rw 0 0
lxc.mount.entry: /mnt/pve/nas-videos media/videos none bind,rw 0 0
...
```
3. restart lxc container

This works for me witout any issues. Thus there is no need any more for me that "the ultimate updater" must be fixed.
