### ISSUE TITLE
[BUG?] bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by wes1993** [BassT23/Proxmox#126]
Hello,
When I run the update or check-updates this warning happen:

```bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)```

Thanks a lot
Stefano

**Comment by BassT23** [comment]
this will come up, if you dont set the locale in the machine.
pls try again, after `sudo dpkg-reconfigure locales`

**Comment by wes1993** [comment]
@BassT23,
Thanks for your reply, I need to do this in all VM? 
Here is the Host
![image](https://github.com/BassT23/Proxmox/assets/52070589/35c2d08f-5e00-453c-ad7d-41209d14a282)

Best regards
Stefano
