### ISSUE TITLE
Feature request: don't wait 45sec on startup VM

### ISSUE THREAD

**Issue by Gauvino** [BassT23/Proxmox#127]
If it's possible, a new way of checking if the VM is up or not than rather waiting 45sec, because maybe some VM need more time and, some less to start up and the script just loses time to update.

**Comment by BassT23** [comment]
And here is my problem. Status say only "stopped" od "running", but running does not mean "totally booted up".
So I must figure out, how Proxmox could tell me "VM booted up completely", ...

**Comment by BassT23** [comment]
I add the start delay time in config, so the user can change this setting easely.
For QEMU it seems that this is the only option. For SSH connection, hopefully I can make more ;)
