### ISSUE TITLE
Script freezes updating docker compose.

### ISSUE THREAD

**Issue by bleach86** [BassT23/Proxmox#141]
I recently updated to 4.1 and the new way that docker is handled is ineffective. It's running find on /.
There are a few issues with this approach. This is very broad and very slow. Even when the containers storage in on a gen4 nvme drive, this never completes. It only eats up ram, forcing a reboot to reclaim. 
Another issue with this approach is compose files can be named anything you want. So searching docker-compose.yaml/yml will not get all compose files.

**Comment by BassT23** [comment]
Hi @bleach86,

for docker issues pls test latest development version with `update develop -up`

**Comment by Gauvino** [comment]
The reason is it's normal for the script when you put `/` as path is go gonna look up inside every folder of the container and the command he did it isn't the best in terms of performance, also we've followed the convention of docker compose naming, and the correct name is the fourth we put in the script.
If you want to search for your docker compose, put them in the same folder inside every container like `/home` and your didn't have any issue with it.

**Comment by bleach86** [comment]
> The reason is it's normal for the script when you put `/` as path is go gonna look up inside every folder of the container and the command he did it isn't the best in terms of performance, also we've followed the convention of docker compose naming, and the correct name is the fourth we put in the script. If you want to search for your docker compose, put them in the same folder inside every container like `/home` and your didn't have any issue with it.
> 
> Edit: are you talking about the recent change on master or develop branch ?

Searching / is hardcoded: https://github.com/BassT23/Proxmox/blob/4a2af2558f37471092669954ea2bac6d37d307c5/update-extras.sh#L89

This is version 4.1 from the main branch.

**Comment by Gauvino** [comment]
Oh ok so please could you update to develop branch with this command please : `update develop -up`

**Comment by bleach86** [comment]
> Hi @bleach86,
> 
> for docker issues pls test latest development version with `update develop -up`

I'm running it now. So far it is doing the same thing.

**Comment by bleach86** [comment]
> > > Hi @bleach86,
> > > for docker issues pls test latest development version with `update develop -up`
> > 
> > 
> > I'm running it now. So far it is doing the same thing.
> 
> Have you put the right folder in the update.conf file ?

this is just a default install. the only change to the config I made was to disable docker because it is just effectively a memory leak.

**Comment by bleach86** [comment]
I see in the dev branch the find is on /home, but I'm seeing it on / still for some reason

**Comment by Gauvino** [comment]
Maybe uninstall the script and reinstall it with develop branch 
To uninstall: bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/master/install.sh) uninstall

**Comment by BassT23** [comment]
> I see in the dev branch the find is on /home, but I'm seeing it on / still for some reason

Pls don't set the path to `/` this result in error. Pls use your correct folder 😉

**Comment by bleach86** [comment]
> > I see in the dev branch the find is on /home, but I'm seeing it on / still for some reason
> 
> Pls don't set the path to `/` this result in error. Pls use your correct folder 😉

I dont see where and it also still appears to be hardcoded anyway. but for some reason even after uninstall and reinstall it is still doing find /. Here is the weird thing. Once it finally finished, it ignored docker in all of my other containers. this container has docker installed, but nothing actually running. My other containers with containers actually installed and running did nothing. update --version says 4.1.2

Didn't this used to update all the docker containers?

**Comment by Gauvino** [comment]
Thanks, you made me think where the problem was and found at that the compose path variable was missing in the develop branch I've actually added it you can now run `update develop -up` and everything should be fine.

**Comment by Gauvino** [comment]
Working for me now !

**Comment by bleach86** [comment]
> Working for me now !

Same here! Not getting stuck and it is actually updating the containers! 

Thanks for the assistance and hard work!
