### ISSUE TITLE
Cron <root@Hostname> /etc/ultimate-updater/check-updates.sh

### ISSUE THREAD

**Issue by xNVrAojkVY** [BassT23/Proxmox#146]
After deinstalling the script I still get the following E-Mail every 12 hours.

```
Cron <root@Hostname> /etc/ultimate-updater/check-updates.sh
/bin/sh: 1: /etc/ultimate-updater/[check-updates.sh](https://check-updates.sh/): not found
```

I can't find the cronjob responsible for this. Where can I find and remove it?
Thanks.

**Comment by Gauvino** [comment]
You should remove from /etc/cron

It's weird that the uninstaller doesn't remove it by it self

**Comment by xNVrAojkVY** [comment]
I think I found it.

It was in /etc/crontab.bak

`
00 07,19 * * *  root    /etc/ultimate-updater/check-updates.sh`
