### ISSUE TITLE
Update script also tried to update the VMs which have been converted to Templates

### ISSUE THREAD

**Issue by Digvijay** [BassT23/Proxmox#154]
Update script also tried to update the VMs which have been converted to Templates which by default fails. There must be a check in place for it to assess if its a VM template and not try to update it  - since in my use case (just an example - it might apply to others and thats why i am creating this issue) these templates don't have a machineid set and a cloud-init template sets up everything them the VM is first created and booted up.

I am not a expert on any shell for that matter so i just would try to suggest some code and not make a PR:

![image](https://github.com/user-attachments/assets/190b2ef1-301d-4dd4-95e3-6d399d88b827)

**Comment by BassT23** [comment]
pls test latest beta release ;)

**Comment by BassT23** [comment]
fixed in latest release ;)
