### ISSUE TITLE
vm with ssh configured break updater in v4.2

### ISSUE THREAD

**Issue by BassT23** [BassT23/Proxmox#164]
working on an fix - please stay tuned

**Comment by hubrikt** [comment]
Sorry to reopen, but still not working for me in my 2 different hosts.
<img width="697" alt="image" src="https://github.com/user-attachments/assets/971c258b-6fba-4f6c-8ae3-3bb34458992f">

**Comment by BassT23** [comment]
Hi @hubrikt,
thanks for your input. To help, I need more input. I cant find "No QEMU guest agent configured" in my script.

The Machine who runs in the error is an VM? - Because of QEMU, ...

Could you please gave me the output of `update status`

**Comment by hubrikt** [comment]
Hello @BassT23 ,
Here the info you request.

<img width="697" alt="image" src="https://github.com/user-attachments/assets/b64097b3-bc0b-4fd5-8166-a60cf54baca0">

It's really strange, as I have same error in 2 different physical hosts, and I have not changed anything in Proxmox config. With previous version of Ultimate Updater was working flawlessly and now I can see this error.

I'll have a look to the potential solution, but I can confirm that QEMU agent was not configured before.

**Comment by BassT23** [comment]
Ok, so the "problematic" VM is configured for ssh update and work before 4.2?

**Comment by hubrikt** [comment]
Correct, you're right. 2 VMs, in 2 different hosts were working withtout QEMU enabled before update.
Anyway, I have installed and enabled QEMU agent on both, and now is working as expected. 

However, I thought that SSH was giving better output 
<img width="697" alt="image" src="https://github.com/user-attachments/assets/e84566f2-bba5-4c98-983b-03fdc6323b9f">

**Comment by BassT23** [comment]
Ok, for clarification;

Before 4.2 you had no qemu installed. Ssh was set and working (best way 😉 )
With 4.2 you run into issue. After installing and enabled qemu, the updater run like it should.

In normal way, if you want to use and configured ssh, qemu should make no problems.

If my description is right now, I will try to reproduce and fix this 😉

**Comment by hubrikt** [comment]
That's correct.
SSH configured in conflicting VMs, following guidance from https://github.com/BassT23/Proxmox/blob/master/ssh.md
Before 4.2, working as expected with no QEMU enabled. 
Since 4.2, only working if QEMU agent installed inside VM and enabled in Proxmox for that VM.

Thanks for your support!

**Comment by BassT23** [comment]
@hubrikt is it correct, that now your "problematic" vm makes update normal (with ssh) now - with enabled qemu?- For me it work.

The "problem" is not really the code part. The problem is, that I check the kernel with qemu command.
So the script identify FreeBSD and skip it for now. FreeBSD and Debian use both OSType l26.

Otherwise I shoud find another option, to identify FreeBSD / non Debian.

**Comment by hubrikt** [comment]
Yes, I think is updating using SSH when QEMU enabled, but as you identified, when disabled QEMU it fails now.
Just for your info, the problematic VM is one with Proxmox Backup Server installed on it. But I thought that Proxmox virtual environment was based in Debian, so not sure why is failing according to your comment.

**Comment by BassT23** [comment]
fixed :)
qemu is not not needed anymore ;)

**Comment by hubrikt** [comment]
Tested and solved!
QEMU removed on VMs and disabled in Proxmox, and updating correctly with 4.2.2 :) Thank you!

Last "little" issue: 
After updating, the system still thinks I have not updated, so asking me again for update every time I try to update (happening in the 2 different hosts). This is the output for `update status`:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/8548122f-7eb8-4cee-b887-6081ebae4a23">

**Comment by BassT23** [comment]
My bad, hadn't change the version in uploaded release file. Will fix it later this day ;)

**Comment by BassT23** [comment]
@hubrikt 
Thx for your help ;)

**Comment by CreegzInCanada** [comment]
Receiving the following error with updating from 4.2.1 to 4.2.3 
![image](https://github.com/user-attachments/assets/1e8c658a-af11-4919-8413-dba1eddcc5a6)
Not clear if there's something I can do to fix that on my end.

**Comment by BassT23** [comment]
@CreegzInCanada 
thanks for the comment.
fixed now ;)

**Comment by CreegzInCanada** [comment]
Brilliant work @BassT23! Thank you <3

**Comment by hubrikt** [comment]
@BassT23 Thank you so much for your great support and such a nice tool.
Brilliant work :)
