### ISSUE TITLE
Feature request docker

### ISSUE THREAD

**Issue by kysersoze81** [BassT23/Proxmox#38]
Requesting basic handling of docker updates for instances inside LXC's
e.g.
`docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>" | sort | uniq | xargs -L1 docker pull
/usr/local/bin/docker-compose -f /home/docker-compose.yml up -d
docker container prune -f 
docker image prune -f
docker system prune -a -f
docker system prune --volumes -f`

commands are [here](https://docs.docker.com/config/pruning/)

**Comment by BassT23** [comment]
******* PLEASE BACKUP IMPORTAND DATA ******* IT'S A BETA *******
You been warned!

First beta released;
try it out.

the script will make a backup from `docker ps` in /root/container_list.bak

first update from development branch with:
`bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/development/install.sh) update`
then u could try it out.

******* PLEASE BACKUP IMPORTAND DATA ******* IT'S A BETA *******

**Comment by BassT23** [comment]
merged to beta stadium, so url has changed:
`bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/beta/install.sh) update`

**Comment by kysersoze81** [comment]
Hi, I didn't see any of the clean-up in the docker section of the script.
Are you avoiding that for right now? Or did I miss something?
I'll try the script over the next day or so

**Comment by BassT23** [comment]
@kysersoze81 you are right, there is no cleaning, for now.
Will try to implement it the next days.
For now, only image update is in, but not working as stable. So it is disabled by default for now.
For testing and give response, the option must be set to `true` in `/root/Proxmox-Updater-Scripts/update-extras.sh`

**Comment by kysersoze81** [comment]
```
Updating e98349757670 image postgres:14
/root/update-extras.sh: line 105: runlike: command not found
Error during Update --- Exit Code: 127

There are an error during update          
Please check Output here or Logfile
```

I don't think it likes your runlike command

This is a Debian 11 LXC

**Comment by BassT23** [comment]
It's crazy,
the problem must be here:

```
      DOCKER_COMMAND="$(runlike "${container}")"
      docker rm --force "${container}"
      eval "${DOCKER_COMMAND}"
```

but, I setup a debian11 container and tested all the commands, and the docker update part. For me it work. But I don't have outdated images, so this part will skip for me.

Does anybody know, how to install an outdated docker image? :D

```
Successfully installed click-8.1.3 runlike-1.4.4
2.9.3: Pulling from portainer/portainer-ce
Digest: sha256:84676dfce8ab328e51990797cceff5131c1ff63c3a73f5ebf1397cad9aa42e3c
Status: Image is up to date for portainer/portainer-ce:2.9.3
docker.io/portainer/portainer-ce:2.9.3
Total reclaimed space: 0B
Total reclaimed space: 0B

root@test-debian:/home/basst# docker ps -q
754fe5412bba

root@test-debian:/home/basst# eval runlike 754fe5412bba
b'docker run --name=portainer --hostname=754fe5412bba --mac-address=xxx --workdir=/ -p 8000:8000 --expose=9000 -p 9443:9443 --restart=no --runtime=runc --detach=true portainer/portainer-ce:2.9.3'

root@test-debian:/home/basst# docker stop portainer
portainer

root@test-debian:/home/basst# eval runlike 754fe5412bba
b'docker run --name=portainer --hostname=754fe5412bba --workdir=/ -p 8000:8000 -p 9443:9443 --restart=no --runtime=runc --detach=true portainer/portainer-ce:2.9.3'
```

**Comment by kysersoze81** [comment]
https://github.com/lavie/runlike
This is runlike. its a container for making other containers 
a normal command to bring the new container online would be `/usr/local/bin/docker-compose -f /home/docker-compose.yml up -d`
[https://docs.docker.com/engine/reference/commandline/docker/](url)
use this for the commands directly. probably better to use docker commands instead of docker-compose
what I'm currently working with for updates and clean-ups is this:
`#!/bin/bash
docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>" | sort | uniq | xargs -L1 docker pull
/usr/local/bin/docker-compose -f /home/docker-compose.yml up -d
docker container prune -f 
docker system prune -a -f
docker image prune -f
docker system prune --volumes -f`

**Comment by BassT23** [comment]
root@test-debian:/home/basst# docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "" | sort | uniq | xargs -L1 docker pull
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Download an image from a registry
root@test-debian:/home/basst# /usr/local/bin/docker-compose -f /home/docker-compose.yml up -d
bash: /usr/local/bin/docker-compose: No such file or directory

What I'm making wrong?

the idea with runlike comes from here:
https://blog.christophersmart.com/2019/12/15/automatically-updating-containers-with-docker/

**Comment by BassT23** [comment]
Ok, heard the first time from compose. Will test it ;)
But for all testing I need an outdated image. How to downgrade one?
Any ideas :)

**Comment by kysersoze81** [comment]
You need to find an older version of the digest file 

[(https://github.com/containers/skopeo))](url)

this allows to you read data from the remote host

You should then be able to pull and old version

**Comment by BassT23** [comment]
please try development version and let me know if it work for you ;)
```
bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/development/install.sh) update
```
```
update
```

**Comment by kysersoze81** [comment]
so first LXC with docker came out like this
```
[Info] Updating LXC 107 : Docker

--- APT UPDATE ---
Hit:1 http://ftp.debian.org/debian bullseye InRelease
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 https://download.docker.com/linux/debian bullseye InRelease [43.3 kB]
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [226 kB]
Get:6 https://download.docker.com/linux/debian bullseye/stable amd64 Packages [18.8 kB]
Fetched 380 kB in 1s (756 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  containerd.io
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.2 MB of archives.
After this operation, 1468 kB of additional disk space will be used.
Get:1 https://download.docker.com/linux/debian bullseye/stable amd64 containerd.io amd64 1.6.18-1 [28.2 MB]
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
apt-listchanges: Reading changelogs...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Fetched 28.2 MB in 2s (12.0 MB/s)
(Reading database ... 37466 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.6.18-1_amd64.deb ...
Unpacking containerd.io (1.6.18-1) over (1.6.16-1) ...
Setting up containerd.io (1.6.18-1) ...
Processing triggers for man-db (2.9.4-2) ...

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---

Recreating home_grafana_1 ... 
Recreating flaresolverr   ... 
Recreating home_teslamate_1 ... 
Recreating home_teslamateagile_1 ... 
Recreating home_mosquitto_1      ... 
Recreating makemkv               ... 
Recreating home_database_1       ... 
Recreating mygaps                ... 
Recreating mygaps                ... done
Recreating home_grafana_1        ... done
Recreating home_mosquitto_1      ... done
Recreating home_teslamateagile_1 ... done
Recreating home_database_1       ... done
Recreating home_teslamate_1      ... done
Recreating makemkv               ... done
Recreating flaresolverr          ... done
```

second one came out like this
```
[Info] Updating LXC 110 : Tdarr

--- APT UPDATE ---
Hit:1 http://ftp.debian.org/debian bullseye InRelease
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 https://download.docker.com/linux/debian buster InRelease [54.0 kB]
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [226 kB]
Get:6 https://download.docker.com/linux/debian buster/stable amd64 Packages [34.0 kB]
Fetched 406 kB in 1s (740 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  containerd.io
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.2 MB of archives.
After this operation, 1468 kB of additional disk space will be used.
Get:1 https://download.docker.com/linux/debian buster/stable amd64 containerd.io amd64 1.6.18-1 [28.2 MB]
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
apt-listchanges: Reading changelogs...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Fetched 28.2 MB in 2s (12.0 MB/s)
(Reading database ... 25729 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.6.18-1_amd64.deb ...
Unpacking containerd.io (1.6.18-1) over (1.6.16-1) ...
Setting up containerd.io (1.6.18-1) ...
Processing triggers for man-db (2.9.4-2) ...

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---


        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
       
``` 
3rd one came out like this
```
[Info] Updating LXC 120 : Hass

--- APT UPDATE ---
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Hit:2 http://ftp.debian.org/debian bullseye InRelease
Get:3 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 https://download.docker.com/linux/debian bullseye InRelease [43.3 kB]
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [226 kB]
Get:6 https://download.docker.com/linux/debian bullseye/stable amd64 Packages [18.8 kB]
Fetched 380 kB in 1s (654 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  containerd.io
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.2 MB of archives.
After this operation, 1468 kB of additional disk space will be used.
Get:1 https://download.docker.com/linux/debian bullseye/stable amd64 containerd.io amd64 1.6.18-1 [28.2 MB]
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
apt-listchanges: Reading changelogs...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Fetched 28.2 MB in 2s (12.0 MB/s)
(Reading database ... 26082 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.6.18-1_amd64.deb ...
Unpacking containerd.io (1.6.18-1) over (1.6.16-1) ...
Setting up containerd.io (1.6.18-1) ...
Processing triggers for man-db (2.9.4-2) ...

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---


        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
        
```

I think its looking in the root folder as by default that's the location where its looking for the docker-compose.yaml
currently i think all of mine are located in 
/home/docker/docker-compose.yml
it might be slow but you might need to do a find operation to see where users are storing the configuration file. or at least check in /home /opt /root and /var

**Comment by BassT23** [comment]
ok, I must implement a search for docker-compose.yaml

**Comment by BassT23** [comment]
please test latest beta with:
bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/beta/install.sh) update

**Comment by kysersoze81** [comment]
`[Info] Updating LXC 107 : Docker

--- APT UPDATE ---
Hit:1 http://ftp.debian.org/debian bullseye InRelease
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Hit:4 https://download.docker.com/linux/debian bullseye InRelease
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [226 kB]
Get:6 http://security.debian.org/debian-security bullseye-security/main Translation-en [148 kB]
Fetched 467 kB in 0s (1,171 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---

Recreating makemkv ... 
Recreating home_database_1 ... 
Recreating flaresolverr    ... 
Recreating home_mosquitto_1 ... 
Recreating home_grafana_1   ... 
Recreating home_teslamate_1 ... 
Recreating mygaps           ... 
Recreating home_teslamateagile_1 ... 
Recreating mygaps                ... done
Recreating home_mosquitto_1      ... done
Recreating home_teslamateagile_1 ... done
Recreating flaresolverr          ... done
Recreating home_grafana_1        ... done
Recreating home_teslamate_1      ... done
Recreating home_database_1       ... done
Recreating makemkv               ... error

ERROR: for makemkv  cannot stop container: b5812ed57d22983419f3be457f4d103738de3184dbf1c6e7dd600e62c5c8f931: tried to kill container, but did not receive an exit event

ERROR: for makemkv  cannot stop container: b5812ed57d22983419f3be457f4d103738de3184dbf1c6e7dd600e62c5c8f931: tried to kill container, but did not receive an exit event
Encountered errors while bringing up the project.`


_Looks like this needs a longer timeout as makemkv did start_

`[Info] Updating LXC 110 : Tdarr

--- APT UPDATE ---
Hit:1 http://ftp.debian.org/debian bullseye InRelease
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Hit:4 https://download.docker.com/linux/debian buster InRelease
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [226 kB]
Get:6 http://security.debian.org/debian-security bullseye-security/main Translation-en [148 kB]
Fetched 467 kB in 0s (1,077 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---


        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml`
_Looks like find isn't working
docker-compose file is in /home/docker/docker-compose.yml_


`[Info] Starting 120 

[Info] Waiting for 120 to start 

[Info] Updating LXC 120 : Hass

--- APT UPDATE ---
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Hit:2 http://ftp.debian.org/debian bullseye InRelease
Hit:3 https://download.docker.com/linux/debian bullseye InRelease
Get:4 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [226 kB]
Get:6 http://security.debian.org/debian-security bullseye-security/main Translation-en [148 kB]
Fetched 467 kB in 0s (1,154 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---


        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
        

[Info] Shutting down 120 `
_looks like the find isn't working
docker-compose.yaml file is stores in /home/hass/docker-compose.yml_

**Comment by BassT23** [comment]
all your 3 systems are debian bullseye
could you check the output from the three systems pls:
`find / -name docker-compose.yaml 2> /dev/null | rev | cut -c 21- | rev`

**Comment by kysersoze81** [comment]
I got a blank output on the find 
also i think that restarting docker.service is only useful for when you loose control over the containers not to restart the containers themselves

**Comment by BassT23** [comment]
ok, please test out this:
`find /home -name docker-compose.yaml 2> /dev/null | rev | cut -c 21- | rev`

does this work better?
The first one brings out permission errors, the last one not, ...

**Comment by kysersoze81** [comment]
Somethings not right
`root@Docker:/#  find /home -name docker-compose.yaml | rev | cut -c 21- | rev`
`root@Docker:/# `
`root@Docker:/# ls -l /home/docker-compose.yml `

`-rw-r--r-- 1 root root 3012 Aug  4  2022 /home/docker-compose.yml`

**Comment by kysersoze81** [comment]
figured it out

`root@Docker:~#  find /home -name *.yml 2> /dev/null | rev | cut -c 21- | rev`
`/hom`
`root@Docker:~# `
`root@Docker:~#  find /home -name *.yml 2> /dev/null `
`/home/docker-compose.yml`
`root@Docker:~# `

Some docker files are yml and some are yaml

**Comment by BassT23** [comment]
Ok, cool, does this then work for you?
`find /home -name docker-compose.* 2> /dev/null | rev | cut -c 21- | rev`

**Comment by kysersoze81** [comment]
`root@Docker:~#  find /home -name docker-compose.* 2> /dev/null | rev | cut -c 21- | rev`
`/hom`
`root@Docker:~# `

**Comment by BassT23** [comment]
please try out latest development branch. I changed from 21 -> 20

`bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/development/install.sh) update`

**Comment by kysersoze81** [comment]
Type [Y/y] for DELETE - enything else will exit rm: cannot remove '/root/Update-Proxmox-Scripts': No such file or directory

**Comment by BassT23** [comment]
k, thats because I changed the directories.
Top

**Comment by kysersoze81** [comment]
*** Updating Docker-Compose ***

*** Update/Upgrade ***
/root/Proxmox-Updater/update-extras.sh: line 86: docker-compose: command not found

**Comment by BassT23** [comment]
ok, than, the soft restart don't work, back to systemctl. Short moment

**Comment by kysersoze81** [comment]
I don't think you seem to be understanding docker. if you run docker-compose -d up then if there is a new image it will restart with the new image. you don't need to restart the docker service just the containers that have been updated

**Comment by BassT23** [comment]
yea, these are my first working with docker-compose
Will try to fix your `did not receive an exit event` error with this help:
https://stackoverflow.com/questions/70434777/cannot-kill-container-container-id-tried-to-kill-container-but-did-not-rece

**Comment by kysersoze81** [comment]
also if you are running a container like tdarr for example it might be 23 hours into a 24 hour operation and having it restart when there isn't an update available would be a waste of time

**Comment by kysersoze81** [comment]
> yea, these are my first working with docker-compose Will try to fix your `did not receive an exit event` error with this help: https://stackoverflow.com/questions/70434777/cannot-kill-container-container-id-tried-to-kill-container-but-did-not-rece

I'd leave that one as I think its more to do with the long startup duration for that container that happens sometimes

**Comment by BassT23** [comment]
ok, than, what did you think we could do, to fix the problems ;)

**Comment by kysersoze81** [comment]
> ok, than, what did you think we could do, to fix the problems ;)



_I had the same when running docker-compose down for one of my containers, everything worked fine again after running docker-compose restart.

I didn't need to restart whole Docker service._
if you could set a 15-20 sec timeout on the "docker-compose -d up" function and then do a docker down then docker up on the container if it exits in that delay period that would work. otherwise i would ignore it as 99% of people are not going to have a container to fail to launch

**Comment by BassT23** [comment]
ok, can build in a 30 sec sleep, just one moment

**Comment by kysersoze81** [comment]
> ok, than, what did you think we could do, to fix the problems ;) The code, you write at the beginning, don't work for me, ...
> 
> docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "" | sort | uniq | xargs -L1 docker pull
> 
> /usr/local/bin/docker-compose -f /home/docker-compose.yml up -d
> 
> docker container prune -f
> 
> docker system prune -a -f
> 
> docker image prune -f
> 
> docker system prune --volumes -f
> 
> so, I'm searching for an option, that also work here on my testing system
> 
> the first line ends in error: "docker pull" requires exactly 1 argument. See 'docker pull --help'.
> 
> Usage: docker pull [OPTIONS] NAME[:TAG|@digest]
> 
> Download an image from a registry

go back to basics. if you just want it to update do a docker pull (insert container name here)

have a look at these links

[https://gist.github.com/ngtrieuvi92/f41b7ecaf6eb6ee18b927100d155bc97](url) 
[https://adamtheautomator.com/update-docker/](url)

**Comment by BassT23** [comment]
Thanks for input.
Will need testing more ;)

**Comment by BassT23** [comment]
so, docker is hard, ...

I think thad could work. For me it did.
But you must use image tag latest.

docker-compose pull
docker-compose up --force-recreate --build -d

with this i updated an old portainer (2.16.1) to newest, without issues.

Implemented in development version.

**Comment by kysersoze81** [comment]
as i said before. you don't want to force the containers to restart unless they actually have a replacement image downloaded

**Comment by BassT23** [comment]
docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "" | sort | uniq | xargs -L1 /usr/local/bin/docker-compose pull
docker-compose up --force-recreate --build -d

These are the code in short for now.
Bash make one after one, so first it make a pull and if it is finished, then it force recreation.

Do you think there should be a sleep between?
Or what do you mean?

**Comment by kysersoze81** [comment]
https://phoenixnap.com/kb/bash-wait-command

again you don't want to use --force-recreate and restart containers that have no updates

**Comment by BassT23** [comment]
ok, now I know what you mean.
Skip recreation for an container, who is already up to date. Right?
Will have a look on it ;)

**Comment by BassT23** [comment]
ok, rebuild and tested.
For me it work.
Please test latest beta branch and give feedback ;)

`bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/beta/install.sh) update`

**Comment by kysersoze81** [comment]
*** A newer version is available ***
       Installed: 3.6.1 / Server: 

Want to update Proxmox-Updater first?
Type [Y/y] or Enter for yes - enything else will skip /dev/fd/63: line 1: 404:: command not found
Error during Update --- Exit Code: 127

There are an error during update          
Please check Output here or Logfile

**Comment by kysersoze81** [comment]
I reinstalled the app and i have had 2 issues
1. `[Info] Updating LXC 119 : Teslalogger

--- APT UPDATE ---
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Hit:2 https://download.mono-project.com/repo/debian stable-buster InRelease
Hit:3 https://download.docker.com/linux/debian bullseye InRelease
Hit:4 http://ftp.debian.org/debian bullseye InRelease
Get:5 http://ftp.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:6 https://packages.microsoft.com/debian/10/prod buster InRelease [5,971 B]
Get:7 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages [154 kB]
Fetched 253 kB in 1s (242 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Searching for extra updates ---
/root/Proxmox-Updater/update-extras.sh: line 81: cd: $'/home/TeslaLogger\n/home/TeslaLogger/TeslaLogger/bin/git': No such file or directory
Error during Update --- Exit Code: 1

There are an error during update          
Please check Output here or Logfile`

2. My tdarr container doesn't run again after its updated. maybe you can set a comparison between running containers before and after the update and start the non running containers by name (the container ID will change)

**Comment by BassT23** [comment]
Please make a
`find /home -name "docker-compose.*" 2> /dev/null | rev | cut -c 20- | rev`
in lxc119.

I think you had more than one line output.
For this I must build in a loop for the docker-compose files.

**Comment by kysersoze81** [comment]
That one has its own git pull function to copy the whole page from github then it pulls the docker for inside the Teslalogger/bin/git folder. basically the file itself is duplicated.
It might actually be better to ignore this container and do it manually because it might cause problems with other peoples setups

**Comment by BassT23** [comment]
> It might actually be better to ignore this container and do it manually because it might cause problems with other peoples setups

For that, you can use `Exclude` Option in config file ;)

>     2. My tdarr container doesn't run again after its updated. maybe you can set a comparison between running containers before and after the update and start the non running containers by name (the container ID will change)
That I made with this:
```
CONTAINER_IMAGE=$(docker inspect --format "{{.Config.Image}}" --type container "${CONTAINER}")
RUNNING_IMAGE=$(docker inspect --format "{{.Image}}" --type container "${CONTAINER}")
LATEST_IMAGE=$(docker inspect --format "{{.Id}}" --type image "${CONTAINER_IMAGE}")
    if [[ ${RUNNING_IMAGE} != "${LATEST_IMAGE}" ]]; then
      echo "Updating ${CONTAINER} image ${CONTAINER_IMAGE}"
      /usr/local/bin/docker-compose up -d --no-deps --build "$NAME"
    fi
```
So, I check Image before pull, and after. And if these are different, I run with name.

I modified a little now, could be an failer in interpretation.
Please recheck after reinstall from beta branch. (Only update will not work, because I don't change version number)

**Comment by kysersoze81** [comment]
I tried to exclude 2 containers with a "," separator and it didn't work was I suppose to use the container name or the container number?

**Comment by BassT23** [comment]
> I tried to exclude 2 containers with a "," separator and it didn't work was I suppose to use the container name or the container number?

Please look the demo ;)
Don't use "," only free space.
"xxx yyy zzz" (the ID)
