### ISSUE TITLE
Feature Request: Add ability to EXCLUDE vm/ct by wild card

### ISSUE THREAD

**Issue by Botched1** [BassT23/Proxmox#46]
I put all of my VM and CT templates in a specific number range (900-999 ID #). It would be nice to be able to exclude a range of ID #s instead of individual ID #s, as if you have a lot of templates it could get painful to add one at a time to the EXCLUDE list.

Maybe something like: "900-999", or "9??". 

Thanks,
Jason

**Comment by BassT23** [comment]
Exclude wildcard does not work for now, hopefully I can manage this.
But what now work is: "ONLY" in config file. Hope this help also for now ;)
Could be tested with latest development branch

**Comment by BassT23** [comment]
I'm searching a little, but the only possability I found is to add a funtion, who allow only one type of caracter.
So in Exclude you could put in "22" - not "22 33".
If so, all machines, who contains 22 in the id, will be skipped.
Does anybody know another bash method to use * or similar in config file?

**Comment by tteck** [comment]
If you skip all templates, you won't have to worry about remembering and noting down IDs, which can help avoid potential issues. Here's the code block that is used in my script.

```
for container in $containers; do
  status=$(pct status $container)
  template=$(pct config $container | grep -q "template:" && echo "true" || echo "false")
   if [ "$template" == "false" ] && [ "$status" == "status: stopped" ]; then
```

**Comment by BassT23** [comment]
There are no response, ...
Should I implement "digit" exclude?
Or is Exclude / Only ok?

**Comment by BassT23** [comment]
> Hi @BassT23
> 
> Could you also add the ability to exclude nodes, we always have a few offline which cause the script to stop running.

Thats a good idea,
I will build in a check, if node is online/reachable before updating (otherwise skip this node), as soon as possible. ;)

**Comment by BassT23** [comment]
@Responseless, this feature is implemented in latest development release ;)
Will do some more changes, before pull to stable, but if you want, you can test it.

**Comment by Responseless** [comment]
@BassT23 Thanks! I just tested and it's working as expected.
