### ISSUE TITLE
Reboot checking should skip not running LXC/VM

### ISSUE THREAD

**Issue by Botched1** [BassT23/Proxmox#53]
With the new reboot checking logic, it will power up shutdown LXC/VMs.

By definition shutdown workloads do not need "reboot".

Logic should skip powering up shutdown LXC/VM for the "reboot check" step.

**Comment by BassT23** [comment]
the script must boot up the machines, for check.
Otherwise it can't check, ...

**Comment by BassT23** [comment]
But please, explain more what you mean. I think I don't understand exacly what you mean :)

**Comment by Botched1** [comment]
If the lxc or VM is stopped, then it will already reboot as soon as it is started.

So you don't need to check if a reboot is needed on an LXC or VM that is already stopped.

**Comment by BassT23** [comment]
ok, now I know what you mean ;)
I will build in the check directly in the update prozedure. Not as separate at the end of the update.

**Comment by BassT23** [comment]
Please test latest developmen branch
`bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/development/install.sh) update`

**Comment by BassT23** [comment]
thats development :D the cluster dont work now.
Sry, need some fixing. The Problem is the new implemented cleaning, ...

**Comment by BassT23** [comment]
now it should work. I tested myself and all work well.
Please test and give feedback ;)
`bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/development/install.sh) update`

**Comment by BassT23** [comment]
implemented in v3.8
