### ISSUE TITLE
ct - <id> Datei hineinschieben | Push file

### ISSUE THREAD

**Issue by Quarkmax** [BassT23/Proxmox#54]
Hallo BassT,

im Gegensatz zum ursprünglichen Script, auf welchem deines aufbaut, erscheint im GUI von Proxmox zu jedem Container **Datei hineinschieben**. 
Was wird da hineingeschoben?

Hello BassT,

in contrast to the original script, on which yours is based, the Proxmox GUI shows **CT <id> - Push file** for each container.
What is being put in there?

Danke | Thanks

**Comment by BassT23** [comment]
Hi Quarkmax,

siehe in update.sh
Zeile 134/135 "pct push"
Das ist einmal die "update-extras.sh" und die "update.conf" um sie dort zu starten.

The push in console come from line 134/135 in update.sh
I push the  "update-extras.sh" and  "update.conf" in the container, to execute it there.

Chears ;)

**Comment by BassT23** [comment]
> im Gegensatz zum ursprünglichen Script, auf welchem deines aufbaut

der ist gut :)
Vom Ursprung ist nicht mehr viel übring :D

**Comment by Quarkmax** [comment]
Vielen Dank und jetzt ist es nachvollziehbar.  
Die Aussage zum_Ursprung_ habe ich aus Deinem Post im ioB Forum genommen. Was so aus 36 Zeilen Code werden kann.... Respekt. 

Danke und 

Chears ;)
