### ISSUE TITLE
[Optimisation] Optimize during update of lxc

### ISSUE THREAD

**Issue by Uruknara** [BassT23/Proxmox#55]
I think that you can push the file to lxc container when making apt and apt upgrade so it take less time to push.

**Comment by BassT23** [comment]
There are several pushes,

in LXC the push is on the end (after cleaning) for "extras" and "update check".
And there are pushes on the beginning, to push all needed files to the host.

I can check, if i can push several files during one push, ...

**Comment by BassT23** [comment]
now I know what you mean ;) but;

there are no global option for extra updates. (but could be implement)
The script pushes the extra file all time. And during run, it check, if extras are installed/enabled.

**Comment by BassT23** [comment]
added "global extra" option in config file
