### ISSUE TITLE
Name changing

### ISSUE THREAD

**Issue by BassT23** [BassT23/Proxmox#56]
Hi @ll,

I need to change the name of the script, because of that:

https://forum.proxmox.com/threads/proxmox-updater-host-lxc-vm.121733/post-542527

Any suggestions?

**Comment by Uruknara** [comment]
Proxmox-Updater does not work ???
You don't like it ?

**Comment by BassT23** [comment]
I like it, but Proxmox not, ...

**Comment by BassT23** [comment]
Brainstorming:

Updater
Ultimate-Updater
Up-To-Date

**Comment by BassT23** [comment]
I had answer from Proxmox Office

`You can also, for example, mention this sentence somewhere: Proxmox® is a registered trademark of Proxmox Server Solutions GmbH.`

I will add the ® Logo with info. So I not need to change the script globally ;)
