### ISSUE TITLE
Root password when updating script and updating LXCs

### ISSUE THREAD

**Issue by hubrikt** [BassT23/Proxmox#63]
After update today to v3.8, when I execute "update up" or "update", I'm being asked constantly for my host root credentials. This was not happening before.

However, even when I entered the password, it returns an error that permission is denied. I'm sure the password is correct as I can login to the host using SSH without issues.

Here some screenshots
<img width="789" alt="image" src="https://user-images.githubusercontent.com/89421789/228331915-9f0cf40c-c4f8-4c4d-8cb5-ca31eb5dd9e1.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/89421789/228332590-39597d54-0d40-4ec3-af9e-d2a15183aece.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/89421789/228332750-47af84cf-6873-4cf2-9e55-0fe936c9edcc.png">

**Comment by BassT23** [comment]
Sry for that, will have a look on it.
During our tests, we don't had this problem.
At first please try to uninstall and install new.

**Comment by BassT23** [comment]
Idea, what comes up, if you type Kratos "ssh root@Kratos"?

**Comment by hubrikt** [comment]
If I type "ssh root@Kratos" I see same behaviour
<img width="724" alt="image" src="https://user-images.githubusercontent.com/89421789/228348948-6e300eeb-b053-4313-8b9d-540d87b53805.png">

However, if I log using IP instead of HostName it works
<img width="724" alt="image" src="https://user-images.githubusercontent.com/89421789/228348589-b9415983-1ddb-4c02-a07e-9c652e77ec00.png">

**Comment by BassT23** [comment]
ok, if you make "cat /etc/hosts" are there a line called "192.168.30.4 foo.bar Kratos"?
I made a change in latest release to use the hostname insead of ip for better readout, but I think I should rollback to IP (for Update Check)
For now you could help yourself, if you put in the line "192.168.30.4 Kratos" in /etc/hosts

**Comment by hubrikt** [comment]
You made the trick!
Issue solved :) I had some misconfiguration on my system, not sure where was coming.

Thanks for your quick support.

**Comment by BassT23** [comment]
gerne ;)
