### ISSUE TITLE
Uninstalling does not remove crontab entry

### ISSUE THREAD

**Issue by Responseless** [BassT23/Proxmox#68]
Uninstalling does not remove crontab entry so errors occur after removing.

emails sent include:
bin/sh: 1: /root/Proxmox-Updater/check-updates.sh: not found

**Comment by BassT23** [comment]
Sad to here, that you want to uninstall.
How did you uninstall?
A little backgroud; the installer make a backup from your crontab file. Then, the uninstaller delete crontab file and restore the backup file.
Could you please gave me the output from ``find /etc/crontab*``

**Comment by BassT23** [comment]
Could it be, that you skip welcome screen uninstall during uninstall?
I think that would cause the issue ;)

**Comment by BassT23** [comment]
fixed in latest development branch
