### ISSUE TITLE
(feat) add support for custom command

### ISSUE THREAD

**Issue by Gauvino** [BassT23/Proxmox#75]
If you can please, does it would be possible to add custom commands to send when updating a (CT) or a (vm)?

And also another feature, add an upgrading script for kernel to it so the script can upgrade kernel of vim and make a settings for it in the config file, with warning and everything because not everyone want to upgrade they're kernel.

**Comment by Uruknara** [comment]
Add an option to add or not the command : -o APT::Get::Always-Include-Phased-Updates=true
for resolving the "package have been kept back" and warning people about the case.

**Comment by BassT23** [comment]
Will have a look on this ;)

**Comment by BassT23** [comment]
Phased Update is in develop version

For the rest, I must look further.

**Comment by Uruknara** [comment]
Cool to see this thanks you !
