### ISSUE TITLE
Reboot VM indication even when restarted

### ISSUE THREAD

**Issue by hubrikt** [BassT23/Proxmox#86]
Hello,

I have this issue since some time ago. I always see in the Welcome-Screen a notification that I need to restart one of my VMs.

<img width="703" alt="image" src="https://github.com/BassT23/Proxmox/assets/89421789/ce52e309-b88c-4615-9b45-4a44d75e7380">

Even when I restart several times this VM and update all LXCs&VMs, the message is still there.
If I have disabled on the update.conf to not monitor this specific VM, obviously, the issue disappears, but I would like to monitor also this one.

Any hint about why this is happening?

**Comment by BassT23** [comment]
Did you check, what `apt update` on the VM sais?
If there is no info about reboot, pleasse make:
```
rm /var/run/reboot-required.pkgs
```
This should fix the problem for now.
If the issue comes on again, let me know ;)

**Comment by BassT23** [comment]
What an os you are running? Which version?

My script check only, if the file `/var/run/reboot-required.pkgs` exist.
If yes, my info will come up.
If the file don`t go after a reboot, there should be a problem with your system, ... (try to google the error)

**Comment by hubrikt** [comment]
Thanks for replying.
`apt update` does not return any reboot info, is updated
<img width="703" alt="image" src="https://github.com/BassT23/Proxmox/assets/89421789/a0a2795b-1a7a-48af-abe3-12c6460a05dc">


OS installed in the VM is Debian 12, but that was also happening with Debian 11.
There does not exist any file called `reboot-required.pkgs` in `/var/run/`
<img width="964" alt="image" src="https://github.com/BassT23/Proxmox/assets/89421789/79fb308e-f81b-474e-bfee-82e33d8d5239">

**Comment by BassT23** [comment]
ok, now it would be crazy. 
Like I said, my script check if the file exist, ...
If the info not go, it looks like the script don`t check the VM correctly :(
There are some problems with docker, ...

please make
```
touch /root/Proxmox-Updater/check-output
```
on the host, where you run the update

this should delete the content of the file, and the info should be gone.

**Comment by hubrikt** [comment]
Now it's fixed.

Thanks for your help. I will report if I see similar issue in the future.
Really appreciated your support.

Cheers.

**Comment by BassT23** [comment]
Thanks ;)
