### ISSUE TITLE
How to disable mail notification

### ISSUE THREAD

**Issue by zoesn89** [BassT23/Proxmox#88]
Hi everyone,

is it possible to disable the mail notification after running the cronjob? I don't even know, where I set up my mailaddress, but I'm getting mails since I installed the proxmox updater.

Thank you!
Felix

**Comment by BassT23** [comment]
Hi,

my script dosn't send emails. So these must be come from your general Proxmox settings.
What are in these emails for informations?
Maybe would it inform you, if a host goes back down after a update?

**Comment by zoesn89** [comment]
Hey,

the email comes from and goes to root@proxmox.fritz.box and says:

Sub: 
Cron <root@proxmox>    /root/Proxmox-Updater/check-updates.sh

Message: 
[1;92mHost[0m : [1;92mproxmox[0m
S: 2 / N: 8
[1;92mVM [36m100[0m : [1;92mvm-debian12[0m
S: 17 / N: 28

I can't remember, where I set up a mail notification🤔

**Comment by BassT23** [comment]
Hi,

hope this help you:
https://forum.proxmox.com/threads/disabling-crontab-mail-notifications.75663/

**Comment by BassT23** [comment]
This issue was closed because it has been inactive for 14 days
