### ISSUE TITLE
DEPENDENCIES

### ISSUE THREAD

**Issue by Pandiora** [BassT23/Proxmox#94]
Err, are you out of your mind?

```
The following additional packages will be installed:
caca-utils chafa fonts-droid-fallback fonts-noto-mono fonts-urw-base35 ghostscript gsfonts hicolor-icon-theme imagemagick imagemagick-6-common imagemagick-6.q16 jp2a libaom3 libcaca0 libcairo-gobject2 libchafa0 libdav1d6 libde265-0 libdeflate0 libdjvulibre-text libdjvulibre21 libfftw3-double3 libfontenc1 libgc1 libgdk-pixbuf-2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgif7 libgomp1 libgpm2 libgs-common libgs10 libgs10-common libheif1 libhwy1 libice6 libid3tag0 libidn12 libijs-0.35 libimath-3-1-29 libimlib2 libjbig0 libjbig2dec0 libjxl0.7 libjxr-tools libjxr0 liblcms2-2 liblerc4 liblqr-1-0 libltdl7 libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6 libnetpbm11 libopenexr-3-1-30 libopenjp2-7 libpaper-utils libpaper1 librsvg2-2 librsvg2-common libsixel-bin libsixel1 libsm6 libspectre1 libtiff6 libwebp7 libwebpdemux2 libwebpmux3 libwmflite-0.2-7 libx265-199 libxt6 netpbm poppler-data shared-mime-info toilet toilet-fonts w3m w3m-img x11-common xfonts-encodings xfonts-utils
Suggested packages:
fonts-noto fonts-freefont-otf | fonts-freefont-ttf fonts-texgyre imagemagick-doc autotrace cups-bsd | lpr | lprng enscript ffmpeg gimp gnuplot grads graphviz hp2xx html2ps libwmf-bin mplayer povray radiance sane-utils texlive-base-bin transfig ufraw-batch xdg-utils libfftw3-bin libfftw3-dev gpm liblcms2-utils inkscape librsvg2-bin poppler-utils fonts-japanese-mincho | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum figlet brotli cmigemo compface dict dict-wn dictd w3m-el xsel
The following additional packages will be installed:
caca-utils chafa fonts-droid-fallback fonts-noto-mono fonts-urw-base35 ghostscript gsfonts hicolor-icon-theme imagemagick imagemagick-6-common imagemagick-6.q16 jp2a libaom3 libcaca0 libcairo-gobject2 libchafa0 libdav1d6 libde265-0 libdeflate0 libdjvulibre-text libdjvulibre21 libfftw3-double3 libfontenc1 libgc1 libgdk-pixbuf-2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgif7 libgomp1 libgpm2 libgs-common libgs10 libgs10-common libheif1 libhwy1 libice6 libid3tag0 libidn12 libijs-0.35 libimath-3-1-29 libimlib2 libjbig0 libjbig2dec0 libjxl0.7 libjxr-tools libjxr0 liblcms2-2 liblerc4 liblqr-1-0 libltdl7 libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6 libnetpbm11 libopenexr-3-1-30 libopenjp2-7 libpaper-utils libpaper1 librsvg2-2 librsvg2-common libsixel-bin libsixel1 libsm6 libspectre1 libtiff6 libwebp7 libwebpdemux2 libwebpmux3 libwmflite-0.2-7 libx265-199 libxt6 netpbm poppler-data shared-mime-info toilet toilet-fonts w3m w3m-img x11-common xfonts-encodings xfonts-utils
Suggested packages:
fonts-noto fonts-freefont-otf | fonts-freefont-ttf fonts-texgyre imagemagick-doc autotrace cups-bsd | lpr | lprng enscript ffmpeg gimp gnuplot grads graphviz hp2xx html2ps libwmf-bin mplayer povray radiance sane-utils texlive-base-bin transfig ufraw-batch xdg-utils libfftw3-bin libfftw3-dev gpm liblcms2-utils inkscape librsvg2-bin poppler-utils fonts-japanese-mincho | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum figlet brotli cmigemo compface dict dict-wn dictd w3m-el xsel
```

The readme claims only neofetch gets installed automatically if it is missing. This would not be a problem to uninstall then huh - but THIS - I do not trust developers being this intransparent. I will just go with tteck's cronjob - does not have such fancy terminal graphicz, but at least it does install a hell of a lot of unwanted dependencies.

**Comment by Pandiora** [comment]
A little correction on my side: One can uninstall all dependencies by the script provided for install. Still there is no mentioning of it in the README. The glorious, fancy welcome screen slows down the connection to the shell noticeably.

Last but not least a word of warning: Do NOT use this in a production environment! It might be alright for homelabs, but even for them scripts from the web should be executed with caution - the installation script seems clean and fine so far.

**Comment by BassT23** [comment]
Sorry, if that is your meaning abou tmy script, but during the  installation, you can say "NO" - to the welcome screen.
For me, I have no problems with neofetch.

I made a little test with a newly Proxmox node setup, and can confirm, that the dependency come from neofetch.

You eaven can't install a unix without a kernel, ...

Like I said, you can use my scrit without neofetch, if you want ;)

Chears

**Comment by Pandiora** [comment]
This all came up because u have chosen a weird way of skipping the installation of the welcome screen or it was a typo. The cmd line says [y/Y] or ENTER to install the welcome screen. I didn't even wanted to install it, hit ENTER, since I didn't read the whole line and then got curious why I had to install so much dependencies only to encounter neofetch relies on them.

This might also be about philosophy - keep it minimalistic would be mine. If I have to install over 30 dependencies (to lazy to count them), just to show some colors and data on the shell prompt, then there is something horribly wrong. Aditionally if the performance degrades noticeably. If you like it - who am I to judge. But the comparison to kernels lacks - or do you want to compare your software or neofetch with kernels?

Anyways, it would help updating the README or make it more clear as to what happens. Some might already use neofetch, but I believe this is a rare scenario for Proxmox. You want to keep your node as clean as possible. And like I wrote, make mentioning of the other parameters your script got.

**Comment by Pandiora** [comment]
I do not use this kind of screens, but on the other hand the colors should be doable - just have a look at some of tteck's scripts. For the system information themselve I'm not sure if this is possible without additional packages. The formatting might be a little bit difficult, but since it is only one screen you want to adjust and not dozens, it does not need to be dynamic.

**Comment by BassT23** [comment]
the first lines from my script comes from tteck ;)

What I can made is a "welcome screen" without neofetch. Like so:

![Unbenannt](https://github.com/BassT23/Proxmox/assets/30832786/f98adec8-1dc4-4601-b0e1-7a1ad3e2818e)

So you don't need any additional installation.

**Comment by Pandiora** [comment]
Okay, that is not the part I saw so far - I just have seen the "screen" with system information and the Proxmox logo in ASCII. But I'm pretty sure you can tweak it so it will look nicely.
