### ISSUE TITLE
[BUG] Docker images not updated because the new Compose commanda is docker compose

### ISSUE THREAD

**Issue by wes1993** [BassT23/Proxmox#96]
Hello,
can you add support for docker compose command, now the docker-compose is deprecated so the check for docker should be using the compose command instaed of docker-compose inside the /usr/local/bin/ directory.

Best Regards
Stefano

**Comment by BassT23** [comment]
fixed in latest development version (v3.9.5 / v1.8.3)

**Comment by wes1993** [comment]
Perfect!! Do you have an ETA for the release?

**Comment by BassT23** [comment]
U can try out with `update develop -up` ;)

**Comment by wes1993** [comment]
Hello,
I have installed the develop branch but there is a BUG witn the extras updates..:

```
--- Searching for extra updates ---
/root/Proxmox-Updater/update-extras.sh: line 84: cd: $'/home/stefano/Containers/Jackett/\n/home/stefano/Containers/nzbhydra2/\n/home/stefano/Containers/Bazarr/\n/home/stefano/Containers/FlaResolverr/': No such file or directory
Error during Update --- Exit Code: 1

There are an error during update
Please check Output here or Logfile
```

Best Regards
Stefano

**Comment by BassT23** [comment]
ok, you use 4 docker-compose files ;)

for this i must implement a loop in script ;)
now, the script work only with one file :)

**Comment by wes1993** [comment]
I have installed the latest develop but now tool tell it's offline but is not true...
```
     https://github.com/BassT23/Proxmox
     ____
    / __ \_________  _  ______ ___  ____  _  __
   / /_/ / ___/ __ \| |/_/ __ `__ \/ __ \| |/_/
  / ____/ /  / /_/ />  </ / / / / / /_/ />  <
 /_/   /_/   \____/_/|_/_/ /_/ /_/\____/_/|_|
      __  __          __      __
     / / / /___  ____/ /___ _/ /____  ____
    / / / / __ \/ __  / __ `/ __/ _ \/ __/
   / /_/ / /_/ / /_/ / /_/ / /_/  __/ /
   \____/ .___/\____/\____/\__/\___/_/
       /_/

            ***  Mode:   Host  ***

 You are offline - Can't update without internet

root@pve:~# apt-get update
Hit:1 http://ftp.it.debian.org/debian bookworm InRelease
Hit:2 http://ftp.it.debian.org/debian bookworm-updates InRelease
Hit:3 http://security.debian.org bookworm-security InRelease
Hit:4 http://download.proxmox.com/debian/pve bookworm InRelease
Hit:5 http://download.proxmox.com/debian/ceph-quincy bookworm InRelease
Reading package lists... Done
```

**Comment by BassT23** [comment]
This is strange, the check will made in update.sh 
But I don't change there anything :(

OK, then try to uninstall first `update uninstall` 
then new install `bash <(curl -s https://raw.githubusercontent.com/BassT23/Proxmox/develop/install.sh)`
and update to develop `update develop -up`

**Comment by wes1993** [comment]
I have done all the steps but still in offline state, just to know how do you check if i'm online or not?

**Comment by BassT23** [comment]
Check is in update.sh (line 64-70)
please try `ping -q -c1 google.com`

**Comment by BassT23** [comment]
please test latest beta with `update beta -up` and give feedback ;)

**Comment by wes1993** [comment]
@BassT23 
Thanks for your support, unfortunately I have changed the ISP and now if i do ping not works... I think tomorrow they will fix this but for now i have edited config and ping to localhost because i know i have internet :-D

During the the my Immich-Container cause error 1:
```
--- Searching for extra updates ---
/root/Proxmox-Updater/update-extras.sh: line 85: cd: /home/immich-app/doc: No such file or directory
Error during Update --- Exit Code: 1
```

The docker compose file is in /home/immich-app not in /home/immich-app/doc i don't know why they try to access to /home/immich-app/doc

Best Regards
Stefano

**Comment by BassT23** [comment]
thanks for feedback ;)

`find /home -name "docker-compose.*" 2> /dev/null | rev | cut -c 20- | rev | tail -n 1`

with this line I search for docker-compose.y(a)ml files.
`tail -n 1` will bring me the last output, which the script use.

so, what give `find /home -name "docker-compose.*"` for an output?

**Comment by wes1993** [comment]
@BassT23 
Thanks again for all your work :-D
Here the output of the command:

```
root@immich ~# find /home -name "docker-compose.*"
/home/immich-app/docker-compose.yml_bck
/home/immich-app/BCK/docker-compose.yml_bad
/home/immich-app/BCK/docker-compose.yml_ok
/home/immich-app/BCK/docker-compose.yml_unless
/home/immich-app/BCK/docker-compose.yml_orig
/home/immich-app/docker-compose.yml
/home/immich-app/docker-compose.yml_old
```

Best Regards
Stefano

**Comment by BassT23** [comment]
Now I see the "problem" :)

The script use the last line: /home/immich-app/docker-compose.yml_old

from this it cut the last 20 caracters.
You named the file `_old` - because of that, the output from the script is:  /home/immich-app/doc

I must better search for *.yml or *.yaml

Will make it as soon as possible :)

**Comment by wes1993** [comment]
@BassT23 Perfect :-D
No problem keep your time :-D
I think the solution could be to search for docker-compose.yaml or docker-compose.yml because the docker compose file name must match one of this or this is wrong? (At this point we will ignore _bck _old or everything else)

**Comment by BassT23** [comment]
so, hopefully fixed these also now :)

**Comment by wes1993** [comment]
Perfect Now works well :-D
